Fix bug when multiple paths included in a fileset (#830)
As an example, adding a modified version of mnist where we read from the
main branch:

```
  "distribution": [
    {
      "@type": "cr:FileObject",
      "@id": "repo",
      "name": "repo",
      "description": "The Hugging Face git repository.",
      "contentUrl": "https://huggingface.co/datasets/mnist/",
      "encodingFormat": "git+https",
      "sha256": "https://github.com/mlcommons/croissant/issues/80"
    },
    {
      "@type": "cr:FileSet",
      "@id": "parquet-files",
      "name": "parquet-files",
      "description": "The underlying Parquet files as converted by Hugging Face (see: https://huggingface.co/docs/datasets-server/parquet).",
      "containedIn": {
        "@id": "repo"
      },
      "encodingFormat": "application/x-parquet",
      "includes": [
        "mnist/train-*.parquet",
        "mnist/test-*.parquet"
      ]
    }
  ]
```

Note the difference w.r.t. the dataset in the 1.0 folder, which reads
from the parquet branch:
```
"distribution": [
    {
      "@type": "cr:FileObject",
      "@id": "repo",
      "name": "repo",
      "description": "The Hugging Face git repository.",
      "contentUrl": "https://huggingface.co/datasets/mnist/tree/refs%2Fconvert%2Fparquet",
      "encodingFormat": "git+https",
      "sha256": "https://github.com/mlcommons/croissant/issues/80"
    },
    {
      "@type": "cr:FileSet",
      "@id": "parquet-files",
      "name": "parquet-files",
      "description": "The underlying Parquet files as converted by Hugging Face (see: https://huggingface.co/docs/datasets-server/parquet).",
      "containedIn": {
        "@id": "repo"
      },
      "encodingFormat": "application/x-parquet",
      "includes": "*/*/*.parquet"
    }
  ]
```

This PR adds a new case in `recursively_populate_jsonld` for plain
strings, which avoids the error:

```
  File "***/croissant/python/mlcroissant/mlcroissant/_src/core/json_ld.py", line 171, in <listcomp>
    value = [recursively_populate_jsonld(child, id_to_node) for child in value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/croissant/python/mlcroissant/mlcroissant/_src/core/json_ld.py", line 166, in recursively_populate_jsonld
    for key, value in entry_node.copy().items():
                      ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'copy'
```